name: amir_diet
# mighty_fitness
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  # sdk: '>=3.3.0 <4.0.0'
  sdk: '>=3.2.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #Basic
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0

  #Network
  http: ^1.2.1
  connectivity_plus: ^5.0.2

  #State Management
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  #Storage
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.25.5
  firebase_analytics: ^10.8.7
  firebase_crashlytics: ^3.4.16
  firebase_auth: ^4.17.6

  #login
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1

  #one signal
  onesignal_flutter: ^5.1.0

  #notification
  awesome_notifications: ^0.9.2

  #Video player
  youtube_player_flutter: ^8.1.2
  chewie: ^1.7.5

  #ads
#  google_mobile_ads: ^2.4.0

  #step count
  pedometer: ^4.0.1

  #gpt
  chat_gpt_flutter: ^1.0.16

  #Other
  fluttertoast: ^8.2.4
  country_code_picker: ^3.0.0
  infinite_listview: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  flutter_html: ^2.2.1
  flutter_tts: ^3.8.5
  draggable_bottom_sheet: ^1.0.2
  share_plus: ^7.2.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_bounce: ^1.1.0
  card_swiper: ^3.0.1
  simple_pip_mode: ^0.8.0
  photo_view: ^0.14.0

  #localizations
  flutter_localizations:
    sdk: flutter

  #chart
  syncfusion_flutter_charts: ^24.2.8
  path_provider: ^2.1.2

  #payment
  razorpay_flutter: ^1.3.6
  flutter_stripe: ^10.0.0
  flutter_paystack: ^1.0.7
  flutter_braintree: ^3.0.0
  flutterwave_standard: ^1.0.8
  flutter_paytabs_bridge: ^2.6.7
  paytm: ^3.0.1
  my_fatoorah: ^3.3.0
  get: ^4.6.6
  shimmer: ^3.0.0

dependency_overrides:
  intl: ^0.18.1
  http: ^0.13.5
  flutter_html: ^2.2.1
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.5
  leak_tracker_flutter_testing: 3.0.3
  leak_tracker_testing: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^3.0.1
             
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/Flag/
  fonts:
    - family: bahij_regular
      fonts:
        - asset: assets/fonts/bahij_regular.ttf
    - family: bahij_bold
      fonts:
        - asset: assets/fonts/bahij_bold.ttf
    - family: Hacen
      fonts:
        - asset: assets/fonts/Hacen_Saudi_Arabia.ttf
    - family: Tajawal-Bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf     
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf  